name: Run Python Script

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '10 1,5,9 * * *' 
  workflow_dispatch:

env:
  TZ: Asia/Shanghai # 确保脚本内部获取的时间也是北京时间

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 安装 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 运行脚本
      env:
        chinaUnicomCookie: ${{ secrets.CHINAU_COOKIE }}
      run: python chinaUnicom.py

    - name: 推送 Bark 通知
      if: always() 
      run: |
        # 使用 date 命令获取格式化后的北京时间
        NOW=$(date "+%H:%M")
        curl -L "https://api.day.app/${{ secrets.BARK_KEY }}/联通脚本/任务于 ${NOW} 执行完毕"
